security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # Accès public à la création de compte
        - { path: ^/user/create, roles: PUBLIC_ACCESS }

        # Accès limité à certaines pages aux utilisateurs connectés
        - { path: ^/panier/valider, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }

        # Accès à toutes les pages d'administration
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/adminformations, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
